# Generated by Django 2.2.28 on 2025-06-26 13:21

from django.db import migrations, models
import django.db.models.deletion
import outpost.django.base.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "logo",
                    models.FileField(upload_to=outpost.django.base.utils.Uuid4Upload),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("number", models.PositiveSmallIntegerField(null=True)),
                ("room", models.CharField(max_length=4, null=True)),
                (
                    "system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="anv.System",
                    ),
                ),
            ],
        ),
    ]
